import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const supportedLocales = <Locale>[Locale('en'), Locale('fr')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'UDB Connect',
      'welcome_back': 'Welcome back',
      'setting_up_interface': 'Setting up interface...',
      'setting_up_experience': 'Setting up your experience',
      'version_label': 'Version 1.0.0',
      'welcome_title': 'Welcome to {appName}',
      'welcome_subtitle': 'Association Platform',
      'welcome_description':
          'Connect, collaborate, and grow with your community members',
      'home': 'Home',
      'news': 'News',
      'events': 'Events',
      'companies': 'Companies',
      'projects': 'Projects',
      'shop': 'Shop',
      'product': 'Product',
      'statistics': 'Statistics',
      'surveys': 'Surveys',
      'profile': 'Profile',
      'directory': 'Directory',
      'notifications': 'Notifications',
      'agenda': 'Agenda',
      'chat': 'Chat',
      'documents': 'Documents',
      'common_all': 'All',
      'pay': 'Pay',
      'retry': 'Retry',
      'loading_dashboard_error': 'We were unable to load your dashboard.',
      'setting_up': 'Setting up',
      'cotisations': 'Subscriptions',
      'approved': 'Approved',
      'pending': 'Pending',
      'rejected': 'Rejected',
      'toggle_language': 'FR',
      'toggle_language_alt': 'EN',
      'language_french_short': 'FR',
      'language_english_short': 'EN',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'login': 'Login',
      'register': 'Register',
      'registering': 'Registering...',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot Password?',
      'email_address': 'Email Address',
      'email_hint': 'Enter your email',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'copyright_notice': '© 2024 UDB Association. All rights reserved.',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'address_optional': 'Address (Optional)',
      'date_of_birth_optional': 'Date of Birth (Optional)',
      'place_of_birth_optional': 'Place of Birth (Optional)',
      'nationality_optional': 'Nationality (Optional)',
      'date_of_first_accession_optional': 'Date of First Accession (Optional)',
      'place_of_residence_optional': 'Place of Residence (Optional)',
      'marital_status_optional': 'Marital Status (Optional)',
      'gender_optional': 'Gender (Optional)',
      'function_optional': 'Function (Optional)',
      'direction_optional': 'Direction (Optional)',
      'single': 'Single',
      'married': 'Married',
      'divorced': 'Divorced',
      'widowed': 'Widowed',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'confirm_password': 'Confirm Password',
      'confirm_password_mismatch':
          'Confirm Password is not the same as Password',
      'search_products_hint': 'Search products...',
      'all_categories': 'All Categories',
      'special_offer': 'Special Offer',
      'special_offer_description': 'Get 20% off on all UDB branded items',
      'shop_now': 'Shop now',
      'products_by_category': 'Products by Category',
      'no_internet_connection': 'No internet connection',
      'failed_to_load_categories': 'Failed to load categories',
      'failed_to_load_products': 'Failed to load products',
      'failed_to_load_user': 'Failed to load user information',
      'check_connection_try_again':
          'Please check your connection and try again.',
      'check_back_later': 'Check back later for new products',
      'no_products_found': 'No products found',
      'failed_to_add_to_cart': 'Failed to add to cart: {message}',
      'udb_association': 'UDB Association',
      'auth_tagline': 'Connect • Collaborate • Grow',
      'empty_field': '{field} is empty',
      'email_required': 'Email is required',
      'invalid_email': 'Invalid email address',
      'password_required': 'Password is required',
      'password_length': 'Password must be 6 characters long.',
      'password_number': 'Password must contain at least one number.',
      'phone_required': 'Phone number is required',
      'invalid_phone': 'Invalid phone number',
      'search_projects_hint': 'Search projects...',
      'status_todo': 'To Do',
      'status_in_progress': 'In Progress',
      'status_to_verify': 'To Verify',
      'status_done': 'Done',
      'filter_all_projects': 'All Projects',
      'filter_completed': 'Completed',
      'filter_incomplete': 'Incomplete',
      'filter_my_projects': 'My Projects',
      'filter_recent': 'Recent',
      'empty_projects_default': 'No projects found',
      'empty_projects_completed': 'No completed projects',
      'empty_projects_assigned': 'No projects assigned to you',
      'empty_projects_incomplete': 'No incomplete projects',
      'empty_projects_recent': 'No recent projects (within 3 days)',
      'empty_projects_branch': 'No projects found for your branch',
      'failed_to_load_projects': 'Failed to load projects',
      'my_branch': 'My Branch',
      'project_start_date': 'Démarrage',
      'project_end_date': 'Livraison',
      'read_more': 'Read more...',
      'read_less': 'Read less...',
      'project_label': 'Project',
      'no_due_date': 'No due date',
      'due_date': 'Due: {date}',
      'due': 'Due:',
      'all_tasks': 'All Tasks',
      'my_tasks': 'My Tasks',
      'tasks_no_tasks_found': 'No tasks found for this project',
      'tasks_no_tasks_assigned': 'No tasks assigned to you for this project',
      'tasks_failed_to_load': 'Failed to load tasks: {error}',
      'tasks_update_status': 'Update Status:',
      'tasks_status_updated': 'Task status updated to {status}',
      'tasks_status_update_failed': 'Failed to update task status: {error}',
      'completion_percentage': '{value}% Complete',
      'documents_search_hint': 'Search documents',
      'documents_recent_title': 'Recent Documents',
      'documents_categories_title': 'Document Categories',
      'documents_all_title': 'All Documents',
      'documents_view_all': 'View All',
      'documents_no_results': 'No documents found',
      'documents_downloading': 'Downloading {title}...',
      'documents_download_success': '{title} downloaded successfully',
      'documents_download_android_media_store':
          'File saved to Downloads folder via MediaStore! Now visible in Downloads app and accessible for sharing via WhatsApp.',
      'documents_download_android_system':
          'File saved to Downloads folder! Check Downloads app or File Manager → Downloads. Should be accessible for sharing via WhatsApp.',
      'documents_download_android_app':
          'File saved to app Downloads folder. Check File Manager → Internal Storage → Android → data → [app_name] → files → Downloads',
      'documents_download_android_default':
          'To find your file: File Manager → Internal Storage → Android → data → [app_name] → files → Documents',
      'documents_download_ios': 'File saved to Files app > Downloads folder.',
      'documents_download_file_info': 'File: {file} ({size} bytes)',
      'documents_download_location': 'Location: {location}',
      'documents_download_path': 'Path: {path}',
      'documents_download_failed': 'Failed to download {title}: {error}',
      'documents_failed_to_load': 'Failed to load documents',
      'documents_unknown_size': 'Unknown size',
      'documents_updated_today': 'Updated today',
      'documents_updated_yesterday': 'Updated yesterday',
      'documents_updated_days_ago': 'Updated {days} days ago',
      'documents_updated_weeks_ago': 'Updated {weeks} weeks ago',
      'documents_updated_recently': 'Updated recently',
      'news_title': 'UDB News',
      'news_search_hint': 'Search',
      'news_filter_title': 'Filter by',
      'news_filter_all': 'All',
      'news_filter_announcements': 'Announcements',
      'news_filter_news': 'News',
      'news_filter_events': 'Events',
      'news_empty': 'No news or events available',
      'news_failed_to_load': 'Failed to load news',
      'news_comments': 'Comments',
      'news_comments_count': '{count} comments',
      'news_no_comments':
          'No comments yet. Be the first to share your thoughts!',
      'news_add_comment_hint': 'Add a comment...',
      'news_post_comment': 'Post',
      'news_comment_posted': 'Comment posted successfully!',
      'news_comment_empty_error': 'Please enter a comment before posting.',
      'news_like_error': 'Unable to update like. Please try again.',
      'news_like_unsupported': 'Likes are not available for this item.',
      'news_label_breaking': 'Breaking',
      'news_label_event': 'Event',
      'news_label_announcement': 'Announcement',
      'profile_failed_to_load': 'Failed to load profile: {error}',
      'directory_title': 'Professional Directory',
      'directory_search_hint': 'Search professionals...',
      'directory_category_all': 'All',
      'directory_category_members': 'Members',
      'directory_category_managers': 'Managers',
      'directory_no_branch':
          'Unable to determine your branch. Please contact support.',
      'directory_empty_query': 'No professionals found for "{query}"',
      'directory_empty_category': 'No professionals found in this category',
      'directory_empty_suggestion':
          'Try adjusting your search or category filter',
      'directory_failed_load_professionals': 'Failed to load professionals',
      'directory_failed_load_profile': 'Failed to load profile',
      'directory_rating_reviews': '{rating} • {reviews} reviews',
      'directory_rating_reviews_zero': '{rating} • No reviews yet',
      'directory_profession_fallback': 'Professional',
      'directory_location_placeholder': 'Location not specified',
      'surveys_refresh_tooltip': 'Refresh & Debug',
      'surveys_test_tooltip': 'Test Survey Responses API',
      'surveys_debug_info_title': 'Debug Info',
      'surveys_debug_close': 'Close',
      'surveys_debug_surveys_status': 'Surveys Status: {status}',
      'surveys_debug_profile_status': 'User Profile Status: {status}',
      'surveys_debug_user_id': 'User ID: {id}',
      'surveys_debug_count': 'Surveys Count: {count}',
      'surveys_test_title': 'Survey Responses API Test',
      'surveys_test_status_code': 'Status Code: {code}',
      'surveys_test_success': 'Success: {success}',
      'surveys_test_body': 'Body: {body}',
      'surveys_already_completed': 'You have already completed this survey',
      'surveys_checking_status': 'Checking survey status...',
      'surveys_status_error': 'Error checking survey status: {error}',
      'surveys_empty_completed_title': 'No Completed Surveys',
      'surveys_empty_completed_subtitle':
          'You haven\'t completed any surveys yet.',
      'surveys_empty_pending_title': 'No Pending Surveys',
      'surveys_empty_pending_subtitle': 'All surveys have been completed!',
      'surveys_empty_all_title': 'No Surveys Available',
      'surveys_empty_all_subtitle':
          'There are no surveys available for your branch at the moment.',
      'surveys_error_title': 'Failed to load surveys',
      'surveys_retry': 'Retry',
      'surveys_filter_all': 'All',
      'surveys_filter_completed': 'Completed',
      'surveys_filter_uncompleted': 'Pending',
      'surveys_status_completed': 'Completed',
      'surveys_status_pending': 'Pending',
      'surveys_status_expired': 'Expired',
      'surveys_status_start': 'Start',
      'surveys_status_submitting': 'Submitting survey...',
      'surveys_loading_title': 'Survey Loading...',
      'surveys_submit_success': 'Survey submitted successfully!',
      'surveys_submit_error': 'Failed to submit survey: {error}',
      'surveys_question_single': '{count} question',
      'surveys_question_plural': '{count} questions',
      'surveys_dialog_title': 'Quick Survey',
      'surveys_dialog_hint': 'Enter your answer...',
      'surveys_option_yes_very_satisfied': 'Yes, very satisfied',
      'surveys_option_needs_improvement': 'No, needs improvement',
      'surveys_option_yes_definitely': 'Yes, definitely',
      'surveys_option_no_probably_not': 'No, probably not',
      'surveys_option_very_likely': 'Very likely',
      'surveys_option_not_likely': 'Not likely',
      'surveys_option_yes': 'Yes',
      'surveys_option_no': 'No',
      'surveys_button_skip': 'Skip',
      'surveys_button_submit': 'Submit',
      'surveys_button_next': 'Next',
      'chat_default_title': 'Chat',
      'chat_messages_title': 'Messages',
      'chat_group_type': 'Group',
      'chat_user_type': 'User',
      'chat_failed_to_load_messages': 'Failed to load messages: {error}',
      'chat_empty_title': 'No messages yet',
      'chat_empty_subtitle': 'Start a conversation with someone',
      'chat_new_chat': 'Start New Chat',
      'chat_unknown_chat': 'Unknown Chat',
      'chat_time_d_ago': '{days}d ago',
      'chat_time_h_ago': '{hours}h ago',
      'chat_time_m_ago': '{minutes}m ago',
      'chat_time_just_now': 'Just now',
      'chat_online_status': 'Online',
      'chat_backend_error':
          'Backend error occurred. Please refresh or contact support.',
      'chat_endpoint_not_found': 'Chat endpoint not found on backend',
      'chat_sql_error': 'Backend SQL error - please contact support',
      'chat_resolve_wrong_chat':
          'Resolve returned wrong chat. Please try again later.',
      'chat_unable_to_resolve': 'Unable to resolve chat',
      'chat_failed_to_send': 'Failed to send message',
      'chat_server_error':
          'Server error. Backend needs to fix ChatController. Please try again later.',
      'chat_login_again': 'Please log in again.',
      'chat_permission_denied': 'You do not have permission to send messages.',
      'chat_invalid_message': 'Invalid message. Please check your input.',
      'chat_new_search_hint': 'Search for users or branches...',
      'chat_new_search_title': 'Search for people',
      'chat_new_search_subtitle':
          'Find users or branches to start a conversation',
      'chat_new_no_results_title': 'No results found',
      'chat_new_no_results_subtitle':
          'No users or branches found for "{query}"',
      'chat_new_error_title': 'Search failed',
      'chat_new_start_failed': 'Failed to start chat: {error}',
      'chat_new_title': 'New Chat',
      'chat_badge_branch': 'Branch',
      'chat_type_message_hint': 'Type a message...',
      'time_period_am': 'AM',
      'time_period_pm': 'PM',
      'cart_title': 'Shopping Cart',
      'cart_empty_title': 'Your cart is empty',
      'cart_empty_subtitle': 'Add some products to get started',
      'cart_total_items_label': 'Total Items:',
      'cart_select_items': 'Select items to checkout',
      'cart_proceed_button': 'Proceed to Checkout ({count})',
      'cart_error_unavailable': 'Cart unavailable',
      'cart_update_failed': 'Failed to update: {error}',
      'cart_item_removed': 'Item removed from cart',
      'cart_delete_failed': 'Failed to delete item: {error}',
      'cart_check_subscription': 'Checking subscription status...',
      'cart_subscription_pending_title': 'Subscription Pending Approval',
      'cart_subscription_pending_message':
          'Your subscription request is pending approval. Please wait for it to be approved before proceeding to checkout.',
      'common_ok': 'OK',
      'common_cancel': 'Cancel',
      'common_retrying': 'Retrying...',
      'checkout_title': 'Checkout',
      'checkout_no_items_title': 'No items selected for checkout',
      'checkout_no_items_subtitle': 'Please select items from your cart',
      'checkout_shipping_address': 'Shipping Address',
      'checkout_order_items': 'Order Items',
      'checkout_payment_methods': 'Payment Methods',
      'checkout_place_order': 'Place Order - Rs. {total}',
      'checkout_processing_order': 'Processing your order...',
      'checkout_select_address_required': 'Please select a shipping address',
      'checkout_no_items_selected': 'No items selected for checkout',
      'checkout_failed_load_cart': 'Failed to load cart: {error}',
      'checkout_order_summary': 'Order Summary',
      'checkout_summary_items': 'Items',
      'checkout_summary_subtotal': 'Subtotal',
      'checkout_summary_shipping': 'Shipping Fee',
      'checkout_summary_tax': 'Tax ({rate}%)',
      'checkout_summary_total': 'Total',
      'checkout_addresses_empty_title': 'No shipping address added yet',
      'checkout_addresses_empty_subtitle':
          'Add a shipping address to continue with checkout',
      'checkout_addresses_add_button': 'Add Shipping Address',
      'checkout_address_select_placeholder': 'Select Shipping Address',
      'checkout_addresses_none_title': 'No addresses found',
      'checkout_addresses_none_subtitle': 'Add your first address to continue',
      'checkout_addresses_error_generic': 'Failed to load addresses',
      'checkout_addresses_error_network': 'No Internet Connection',
      'checkout_addresses_error_generic_subtitle':
          'Something went wrong. Please try again.',
      'checkout_addresses_error_network_subtitle':
          'Please check your internet connection and try again.',
      'checkout_retrying': 'Retrying...',
      'checkout_add_address_title': 'Add New Address',
      'checkout_field_first_name': 'First Name *',
      'checkout_field_first_name_required': 'First name is required',
      'checkout_field_last_name': 'Last Name *',
      'checkout_field_last_name_required': 'Last name is required',
      'checkout_field_address_line1': 'Address Line 1 *',
      'checkout_field_address_required': 'Address is required',
      'checkout_field_city': 'City',
      'checkout_field_state': 'State',
      'checkout_field_zip': 'Zip Code',
      'checkout_field_country': 'Country',
      'checkout_field_phone': 'Phone',
      'checkout_set_default_address': 'Set as default address',
      'checkout_cancel': 'Cancel',
      'checkout_add_address': 'Add Address',
      'checkout_address_success': 'Address added successfully!',
      'checkout_address_error': 'Failed to add address: {error}',
      'checkout_order_failed': 'Order failed: {error}',
      'checkout_payment_processing': 'Processing...',
      'checkout_submit_request': 'Submit Request',
      'checkout_pay_amount': 'Pay \$ {amount}',
      'checkout_item_unit': 'Unit: Rs. {price}',
      'checkout_item_quantity': 'Qty: {quantity}',
      'order_confirmation_title': 'Order Confirmation',
      'order_success_message': 'Order Placed Successfully!',
      'order_number_display': 'Order #{number}',
      'order_summary_title': 'Order Summary',
      'order_summary_subtotal': 'Subtotal',
      'order_summary_shipping_fee': 'Shipping Fee',
      'order_summary_tax': 'Tax',
      'order_summary_total': 'Total',
      'order_number_label': 'Order Number',
      'order_status_label': 'Status',
      'order_payment_status_label': 'Payment Status',
      'order_total_amount_label': 'Total Amount',
      'order_shipping_address_title': 'Shipping Address',
      'order_items_title': 'Order Items',
      'order_items_empty': 'No items in this order.',
      'order_item_quantity': 'Qty: {quantity}',
      'order_item_price': 'Rs. {price}',
      'order_product_fallback': 'Product',
      'order_back_to_cart': 'Back to Cart',
      'order_continue_shopping': 'Continue Shopping',
      'order_status_pending': 'Pending',
      'order_status_processing': 'Processing',
      'order_status_completed': 'Completed',
      'order_status_cancelled': 'Cancelled',
      'order_payment_status_paid': 'Paid',
      'order_payment_status_pending': 'Pending',
      'order_payment_status_failed': 'Failed',
      'order_payment_status_unpaid': 'Unpaid',
      'order_payment_status_refunded': 'Refunded',
      'order_details_title': 'Order Details',
      'order_details_load_failed': 'Failed to load order details',
      'order_detail_ordered_on': 'Ordered on {date}',
      'order_payment_status_display': 'Payment: {status}',
      'order_detail_sku': 'SKU: {sku}',
      'order_phone_label': 'Phone: {phone}',
      'order_review_section_title': 'Rate Your Delivered Products',
      'order_review_section_subtitle':
          'Share your experience with the products you received',
      'order_review_rating_label': 'Rating *',
      'order_review_title_label': 'Review Title (Optional)',
      'order_review_title_hint': 'Sum up your experience',
      'order_review_body_label': 'Your Review (Optional)',
      'order_review_body_hint': 'Share your thoughts about this product',
      'order_review_submit_button': 'Submit Review',
      'order_review_select_rating_error': 'Please select a rating',
      'order_review_submit_success': 'Review submitted for {product}',
      'order_review_submit_error': 'Failed to submit review: {error}',
      'companies_title': 'ORGANES',
      'organes_title': 'ORGANES',
      'organes_divisions': 'Divisions',
      'organes_effectif': 'Effectif',
      'organes_agents': 'Agents',
      'organes_search_hint': 'Recherche',
      'organes_description': 'Description',
      'organes_contact': 'Contact',
      'organes_province': 'Province',
      'organes_departement': 'Département',
      'organes_commune': 'Commune / Localité',
      'organes_arrondissement': 'Arrondissemnt',
      'companies_description':
          'Connecting builders, fostering development, and building a stronger community together.',
      'companies_section_title': 'Our Companies',
      'companies_empty_state': 'No companies found',
      'companies_error_loading': 'Error loading companies',
      'events_calendar_title': 'Calendar',
      'events_day_sun': 'Sun',
      'events_day_mon': 'Mon',
      'events_day_tue': 'Tue',
      'events_day_wed': 'Wed',
      'events_day_thu': 'Thu',
      'events_day_fri': 'Fri',
      'events_day_sat': 'Sat',
      'events_filter_all': 'All',
      'events_filter_events': 'Events',
      'events_filter_meetings': 'Meetings',
      'events_today_title': "Today's Events",
      'events_no_events_for_date': 'No events for this date',
      'events_upcoming_title': 'Upcoming Events',
      'events_no_location': 'No location',
      'events_scope_global': 'Global',
      'events_scope_branch': 'Branch',
      'events_all_day': 'All day',
      'events_error_title': 'Failed to load events',
      'events_date_start': 'Start date',
      'events_date_end': 'End date',
      'events_location': 'Location',
      'events_contact_person': 'Person to contact',
      'events_no_contact_person': 'No contact person available',
      'detail_author': 'Author',
      'detail_author_label': 'Author : ',
      'detail_at': 'at',
      'profile_error_load': 'Failed to load profile',
      'profile_plan_unknown': 'Unknown',
      'profile_personal_info_title': 'Personal Information',
      'profile_personal_full_name': 'Full Name',
      'profile_personal_email': 'Email',
      'profile_personal_phone': 'Phone Number',
      'profile_personal_member_since': 'Member Since',
      'profile_personal_member_since_unknown': 'Not available',
      'profile_personal_edit': 'Edit Information',
      'profile_address_hint': 'Address',
      'profile_business_name': 'Business Name',
      'profile_shop_details': 'Shop Details',
      'profile_update_name_required': 'Name is required',
      'profile_update_phone_required': 'Phone number is required',
      'profile_update_success': 'Profile updated successfully!',
      'profile_update_failed': 'Failed to update profile: {error}',
      'profile_update_in_progress': 'Updating...',
      'profile_update_button': 'Update Profile',
      'edit_profile_pick_image_failed': 'Failed to pick image: {error}',
      'edit_profile_load_error': 'Failed to load profile: {error}',
      'profile_orders_title': 'My Orders',
      'profile_orders_refreshing': 'Refreshing...',
      'profile_orders_refresh_tooltip': 'Refresh Orders',
      'profile_orders_empty_title': 'No orders yet',
      'profile_orders_empty_subtitle': 'Your orders will appear here',
      'profile_orders_error_title': 'Failed to load orders',
      'common_not_available': 'N/A',
      'logout': 'Logout',
      'notifications_header_title': 'Stay Connected',
      'notifications_header_subtitle':
          'Get personalized notifications for reminders, new posts, and important updates',
      'notifications_settings_title': 'Notification Settings',
      'notifications_event_title': 'Event Reminders',
      'notifications_event_subtitle': 'Get notified before events',
      'notifications_posts_title': 'New Posts',
      'notifications_posts_subtitle': 'Stay updated with latest posts',
      'notifications_announcements_title': 'Announcements',
      'notifications_announcements_subtitle': 'Important association updates',
      'notifications_recent_title': 'Recent Notifications',
      'notifications_empty': 'No notifications yet',
      'notifications_load_failed': 'Failed to load notifications',
      'notifications_mark_read_success': 'Notification marked as read',
      'notifications_mark_read_failure':
          'Failed to mark notification as read: {error}',
      'notifications_badge_new': 'NEW',
      'notifications_smart_title': 'Smart Notifications',
      'notifications_smart_subtitle': 'Customize your experience',
      'notifications_sound': 'Sound',
      'notifications_vibration': 'Vibration',
      'orders_empty_title': 'No orders yet',
      'orders_empty_subtitle':
          'Your orders will appear here when you make a purchase',
      'orders_start_shopping': 'Start Shopping',
      'orders_unavailable': 'Orders unavailable',
      'orders_check_connection': 'Check Connection',
      'orders_load_more': 'Load More Orders',
      'orders_load_more_failed': 'Failed to load more orders: {error}',
      'common_loading': 'Loading...',
      'common_user_placeholder': 'User',
      'membership_dialog_title': 'Choose Subscription Type',
      'membership_dialog_subtitle':
          'Select the type of subscription you want to purchase:',
      'membership_option_member_title': 'Become a Member',
      'membership_option_member_description':
          'Access premium member features and benefits',
      'membership_option_vendor_title': 'Become a Vendor',
      'membership_option_vendor_description':
          'Sell products and manage your store',
      'membership_option_user_title': 'Become a Special User',
      'membership_option_user_description':
          'Access special user features and privileges',
      'subscription_subscribe_now': 'Subscribe Now',
      'subscription_renew_button': 'Renew Subscription',
      'profile_membership_title': 'Membership Status',
      'profile_membership_current_plan': 'Current Plan',
      'profile_membership_expiry': 'Expiry Date',
      'profile_membership_expired_body': 'Your subscription has expired',
      'profile_membership_days_remaining': 'Days Remaining',
      'profile_membership_day_singular': '{count} day',
      'profile_membership_days_plural': '{count} days',
      'profile_membership_progress_title': 'Subscription Progress',
      'profile_vendor_status_title': 'Vendor Status',
      'profile_user_subscription': 'User Subscription Status',
      'membership_no_subscription_title': 'No subscription yet',
      'membership_no_subscription_user_hint':
          'Subscribe to access premium features',
      'membership_no_subscription_vendor_hint':
          'Get a vendor subscription to access all features',
      'membership_no_subscription_member_hint':
          'Get a membership to access all features',
      'membership_pending_title': 'Subscription Pending',
      'membership_pending_message':
          'Your subscription request is pending approval. Please wait for admin approval.',
      'membership_active_title': 'Subscription Active',
      'membership_active_message':
          'Your subscription is active and you have access to all features.',
      'membership_expired_title': 'Subscription Expired',
      'membership_expired_message':
          'Your subscription has expired. Renew to continue accessing premium features.',
      'membership_progress_expired': 'Subscription has expired',
      'membership_progress_expires_tomorrow': 'Expires tomorrow',
      'membership_progress_expires_soon':
          'Expires in {count} days - renew soon!',
      'membership_progress_expires_days': 'Expires in {count} days',
      'membership_progress_just_started':
          'Subscription just started ({remaining} of {total} days remaining)',
      'membership_progress_early':
          'Early in subscription period ({remaining} of {total} days remaining)',
      'membership_progress_midway':
          'Midway through subscription ({remaining} of {total} days remaining)',
      'membership_progress_near_end':
          'Near end of subscription period ({remaining} of {total} days remaining)',
      'drawer_explore_services': 'Explore our services and stay connected.',
      'drawer_footer': '© 2024 UDB Association. All rights reserved.',
      'drawer_premium_title': 'Become a Premium Member',
      'drawer_premium_description':
          'Unlock exclusive benefits designed to elevate your experience.',
      'survey_analysis_title': 'UDB Survey',
      'survey_analysis_total_responses': 'Total Responses',
      'survey_analysis_active_surveys': 'Active Surveys',
      'survey_analysis_recent_title': 'Recent Surveys',
      'survey_analysis_questions_responses':
          '{questions} questions • {responses}/{total} responses',
      'survey_analysis_completion_rate': 'Completion Rate',
      'survey_analysis_analytics_title': 'Analytics',
      'survey_analysis_responses_over_time': 'Survey Responses Over Time',
      'survey_analysis_error_title': 'Failed to Load Survey Analysis',
      'all_surveys_title': 'All Surveys',
      'all_surveys_empty_title': 'No Surveys Available',
      'all_surveys_empty_subtitle': 'There are no surveys to display.',
      'all_surveys_count_single': '{count} survey',
      'all_surveys_count_plural': '{count} surveys',
      'all_surveys_error_title': 'Failed to Load Surveys',
      'statistics_title': 'Statistics & Analysis',
      'statistics_error_title': 'Failed to load statistics',
      'statistics_overview': 'Overview',
      'statistics_total_orders': 'Total Orders',
      'statistics_total_revenue': 'Total Revenue',
      'statistics_total_customers': 'Total Customers',
      'statistics_avg_order_value': 'Avg Order Value',
      'statistics_currency_value': '\${value}',
      'statistics_sales_progress_title': '{period} Sales Progress',
      'statistics_period_weekly': 'Weekly',
      'statistics_period_monthly': 'Monthly',
      'statistics_period_yearly': 'Yearly',
      'statistics_select_month': 'Select Month',
      'statistics_week_label': 'Week {week}',
      'statistics_select_week_title': 'Select Week - {month}',
      'statistics_order_status_title': 'Order Status',
      'statistics_orders_count': '{count} orders',
      'statistics_status_pending': 'Pending',
      'statistics_status_processing': 'Processing',
      'statistics_status_shipped': 'Shipped',
      'statistics_status_delivered': 'Delivered',
      'manager_statistics_title': 'Statistics & Reports',
      'manager_statistics_members': 'Total Members',
      'manager_statistics_events': 'Total Events',
      'manager_statistics_monthly_progress': 'Monthly Progress',
      'manager_statistics_quick_stats': 'Quick Statistics',
      'manager_statistics_new_subscriptions': 'New Subscriptions',
      'manager_statistics_this_month': 'This month',
      'manager_statistics_events_organized': 'Events Organized',
      'manager_statistics_subscription_trends': 'Subscription Trends',
      'manager_statistics_select_duration': 'Select Duration',
      'manager_statistics_duration_last_month': 'Last Month',
      'manager_statistics_duration_last_6_months': 'Last 6 months',
      'manager_statistics_duration_last_year': 'Last Year',
      'manager_statistics_legend_new': 'New',
      'manager_statistics_legend_renewed': 'Renewed',
      'manager_statistics_error_subscriptions': 'Failed to load subscriptions',
      'drawer_become_member_button': 'Become a Member',
      'drawer_survey_analysis': 'Survey Analysis',
      'drawer_error_title': 'Unable to load menu',
      'profile_header_title': 'My Profile',
      'profile_header_member_id': 'Member ID: {id}',
      'profile_header_member_id_default': 'Member ID: UDB-2024-001',
      'profile_header_become_member': 'Become a Member',
      'footer_become_member_snackbar':
          'Become a member to unlock this feature.',
      'profile_header_become_vendor': 'Become a Seller',
      'profile_badge_basic': 'Basic Member',
      'profile_badge_standard': 'Standard Member',
      'profile_badge_premium': 'Premium Member',
      'product_detail_title': 'Product Detail',
      'product_detail_not_found': 'Product not found',
      'product_detail_not_available': 'Product not available',
      'product_detail_discount_badge': '{percent}% OFF',
      'product_detail_reviews_summary': '{rating} ({count} reviews)',
      'product_detail_customer_reviews': 'Customer Reviews',
      'product_detail_reviews_count': '{count} reviews',
      'product_detail_reviews_count_zero': '0 reviews',
      'product_detail_no_reviews_yet': 'No reviews yet',
      'product_detail_be_first_review': 'Be the first to review this product!',
      'product_detail_load_more_reviews': 'Load More Reviews',
      'product_detail_failed_to_load_reviews': 'Failed to load reviews',
      'product_detail_reviews_try_again': 'Please try again later.',
      'product_detail_review_anonymous': 'Anonymous',
      'product_detail_review_verified': 'Verified Review',
      'product_detail_in_stock': 'In stock ({count} available)',
      'product_detail_out_of_stock': 'Out of stock',
      'product_detail_description_title': 'Description',
      'product_detail_specifications_title': 'Specifications',
      'product_detail_spec_sku': 'SKU',
      'product_detail_spec_weight': 'Weight',
      'product_detail_spec_weight_value': '{weight} kg',
      'product_detail_spec_dimensions': 'Dimensions',
      'product_detail_shop_info_title': 'Shop Information',
      'product_detail_no_tagline': 'No tagline available',
      'product_detail_related_products_title': 'Related Products',
      'product_detail_add_to_cart': 'Add to Cart',
      'product_detail_add_to_cart_success': '{product} added to cart!',
      'product_detail_add_to_cart_error': 'Failed to add to cart: {error}',
      'product_detail_video_error_empty': 'Empty video URL',
      'product_detail_video_error_unreachable': 'Cannot reach video URL',
      'product_detail_video_error_playback': 'Video playback error',
      'product_detail_video_error_initialization': 'Failed to initialize video',
      'product_detail_video_loading': 'Loading video...',
      'subscription_selection_title': 'Choose Subscription',
      'subscription_selection_heading': 'Choose Your Plan',
      'subscription_selection_badge_popular': 'Most Popular',
      'subscription_selection_button_contact_sales': 'Contact Sales',
      'subscription_selection_button_choose': 'Choose {plan}',
      'subscription_selection_button_choose_generic': 'Choose Plan',
      'subscription_selection_error': 'Error loading subscriptions: {error}',
      'subscription_checkout_title': 'Checkout',
      'subscription_checkout_user_success':
          'Your subscription has been placed. Wait for the admin approval.',
      'subscription_checkout_member_success':
          'Your subscription request has been submitted successfully. Kindly wait for the admin to approve your account.',
      'subscription_checkout_vendor_success':
          'Your payment is successful. Kindly wait for the admin to approve your account.',
      'subscription_checkout_activation_failed':
          'Subscription activation failed: {error}',
      'subscription_checkout_request_failed':
          'Subscription request failed: {error}',
      'subscription_checkout_payment_failed': 'Payment failed: {error}',
      'subscription_checkout_user_not_authenticated': 'User not authenticated',
      'subscription_checkout_processing': 'Processing...',
      'subscription_checkout_submit_request': 'Submit Request',
      'subscription_checkout_pay_amount': 'Pay \$ {amount}',
      'subscription_summary_plan_label': '{plan} Plan',
      'subscription_summary_includes': 'Includes:',
      'subscription_checkout_error': 'Error: {error}',
      'subscription_order_summary': 'Order Summary',
      'subscription_order_subtotal': 'Subtotal',
      'subscription_order_discount': 'Discount',
      'subscription_order_total': 'Total',
    },
    'fr': {
      'app_name': 'UDB Connect',
      'welcome_back': 'Bon retour',
      'setting_up_interface': 'Configuration de l’interface…',
      'setting_up_experience': 'Configuration de votre expérience',
      'version_label': 'Version 1.0.0',
      'welcome_title': 'Bienvenue sur {appName}',
      'welcome_subtitle': 'Plateforme de l’association',
      'welcome_description':
          'Connectez-vous, collaborez et développez-vous avec les membres de votre communauté',
      'home': 'Accueil',
      'news': 'Actualités',
      'events': 'Événements',
      'companies': 'Entreprises',
      'projects': 'Projets',
      'shop': 'Boutique',
      'product': 'Produits',
      'statistics': 'Statistiques',
      'surveys': 'Enquêtes',
      'profile': 'Compte',
      'directory': 'Annuaire',
      'notifications': 'Notifications',
      'agenda': 'Agenda',
      'chat': 'Chat',
      'documents': 'Documents',
      'common_all': 'Tout',
      'pay': 'Paiement',
      'retry': 'Réessayer',
      'loading_dashboard_error':
          'Nous n’avons pas pu charger votre tableau de bord.',
      'setting_up': 'Configuration',
      'cotisations': 'Cotisations',
      'approved': 'Validée',
      'pending': 'En attente',
      'rejected': 'Rejetée',
      'toggle_language': 'EN',
      'toggle_language_alt': 'FR',
      'language_french_short': 'FR',
      'language_english_short': 'EN',
      'sign_in': 'Se connecter',
      'create_account': 'Créer un compte',
      'login': 'Connexion',
      'register': 'S’inscrire',
      'registering': 'Inscription…',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié ?',
      'email_address': 'Adresse e-mail',
      'email_hint': 'Entrez votre e-mail',
      'password': 'Mot de passe',
      'password_hint': 'Entrez votre mot de passe',
      'copyright_notice': '© 2024 Association UDB. Tous droits réservés.',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'email': 'E-mail',
      'phone_number': 'Numéro de téléphone',
      'address_optional': 'Adresse (optionnel)',
      'date_of_birth_optional': 'Date de naissance (optionnel)',
      'place_of_birth_optional': 'Lieu de naissance (optionnel)',
      'nationality_optional': 'Nationalité (optionnel)',
      'date_of_first_accession_optional': 'Date de première adhésion (optionnel)',
      'place_of_residence_optional': 'Lieu de résidence (optionnel)',
      'marital_status_optional': 'Statut matrimonial (optionnel)',
      'gender_optional': 'Genre (optionnel)',
      'function_optional': 'Fonction (optionnel)',
      'direction_optional': 'Direction (optionnel)',
      'single': 'Célibataire',
      'married': 'Marié(e)',
      'divorced': 'Divorcé(e)',
      'widowed': 'Veuf(ve)',
      'male': 'Homme',
      'female': 'Femme',
      'other': 'Autre',
      'confirm_password': 'Confirmez le mot de passe',
      'confirm_password_mismatch':
          'La confirmation ne correspond pas au mot de passe',
      'search_products_hint': 'Rechercher des produits…',
      'all_categories': 'Toutes les catégories',
      'special_offer': 'Offre spéciale',
      'special_offer_description':
          'Obtenez 20 % de réduction sur tous les articles UDB',
      'shop_now': 'Acheter',
      'products_by_category': 'Produits par catégorie',
      'no_internet_connection': 'Pas de connexion Internet',
      'failed_to_load_categories': 'Échec du chargement des catégories',
      'failed_to_load_products': 'Échec du chargement des produits',
      'failed_to_load_user': 'Échec du chargement des informations utilisateur',
      'check_connection_try_again':
          'Veuillez vérifier votre connexion et réessayer.',
      'check_back_later':
          'Revenez plus tard pour découvrir de nouveaux produits',
      'no_products_found': 'Aucun produit trouvé',
      'failed_to_add_to_cart': 'Échec de l’ajout au panier : {message}',
      'udb_association': 'Association UDB',
      'auth_tagline': 'Connecter • Collaborer • Progresser',
      'empty_field': '{field} est vide',
      'email_required': 'L’e-mail est requis',
      'invalid_email': 'Adresse e-mail invalide',
      'password_required': 'Le mot de passe est requis',
      'password_length': 'Le mot de passe doit contenir 6 caractères.',
      'password_number': 'Le mot de passe doit contenir au moins un chiffre.',
      'phone_required': 'Le numéro de téléphone est requis',
      'invalid_phone': 'Numéro de téléphone invalide',
      'search_projects_hint': 'Rechercher des projets…',
      'status_todo': 'À faire',
      'status_in_progress': 'En cours',
      'status_to_verify': 'À vérifier',
      'status_done': 'Terminé',
      'filter_all_projects': 'Tous les projets',
      'filter_completed': 'Terminés',
      'filter_incomplete': 'Incomplets',
      'filter_my_projects': 'Mes projets',
      'filter_recent': 'Récents',
      'empty_projects_default': 'Aucun projet trouvé',
      'empty_projects_completed': 'Aucun projet terminé',
      'empty_projects_assigned': 'Aucun projet ne vous est attribué',
      'empty_projects_incomplete': 'Aucun projet incomplet',
      'empty_projects_recent': 'Aucun projet récent (moins de 3 jours)',
      'empty_projects_branch': 'Aucun projet trouvé pour votre branche',
      'failed_to_load_projects': 'Échec du chargement des projets',
      'my_branch': 'Ma branche',
      'project_start_date': 'Démarrage',
      'project_end_date': 'Livraison',
      'read_more': 'Lire la suite...',
      'read_less': 'Lire moins...',
      'project_label': 'Projet',
      'no_due_date': 'Aucune date limite',
      'due_date': 'Échéance : {date}',
      'due': 'Échéance :',
      'all_tasks': 'Toutes les tâches',
      'my_tasks': 'Mes tâches',
      'tasks_no_tasks_found': 'Aucune tâche trouvée pour ce projet',
      'tasks_no_tasks_assigned': 'Aucune tâche assignée pour ce projet',
      'tasks_failed_to_load': 'Échec du chargement des tâches : {error}',
      'tasks_update_status': 'Mettre à jour le statut :',
      'tasks_status_updated': 'Statut de la tâche mis à jour vers {status}',
      'tasks_status_update_failed': 'Échec de la mise à jour du statut de la tâche : {error}',
      'completion_percentage': '{value} % terminé',
      'documents_search_hint': 'Rechercher des documents',
      'documents_recent_title': 'Documents récents',
      'documents_categories_title': 'Catégories de documents',
      'documents_all_title': 'Tous les documents',
      'documents_view_all': 'Tout afficher',
      'documents_no_results': 'Aucun document trouvé',
      'documents_downloading': 'Téléchargement de {title}…',
      'documents_download_success': '{title} téléchargé avec succès',
      'documents_download_android_media_store':
          'Fichier enregistré dans le dossier Téléchargements via MediaStore ! Visible dans l’application Téléchargements et partageable via WhatsApp.',
      'documents_download_android_system':
          'Fichier enregistré dans Téléchargements ! Consultez l’application Téléchargements ou Gestionnaire de fichiers → Téléchargements. Partage WhatsApp possible.',
      'documents_download_android_app':
          'Fichier enregistré dans le dossier Téléchargements de l’application. Gestionnaire de fichiers → Stockage interne → Android → data → [app_name] → files → Downloads',
      'documents_download_android_default':
          'Pour retrouver le fichier : Gestionnaire de fichiers → Stockage interne → Android → data → [app_name] → files → Documents',
      'documents_download_ios':
          'Fichier enregistré dans Fichiers > Téléchargements.',
      'documents_download_file_info': 'Fichier : {file} ({size} octets)',
      'documents_download_location': 'Emplacement : {location}',
      'documents_download_path': 'Chemin : {path}',
      'documents_download_failed':
          'Échec du téléchargement de {title} : {error}',
      'documents_failed_to_load': 'Échec du chargement des documents',
      'documents_unknown_size': 'Taille inconnue',
      'documents_updated_today': 'Mis à jour aujourd’hui',
      'documents_updated_yesterday': 'Mis à jour hier',
      'documents_updated_days_ago': 'Mis à jour il y a {days} jours',
      'documents_updated_weeks_ago': 'Mis à jour il y a {weeks} semaines',
      'documents_updated_recently': 'Mis à jour récemment',
      'news_title': 'Actualités UDB',
      'news_search_hint': 'Rechercher',
      'news_filter_title': 'Filtrer par',
      'news_filter_all': 'Tout',
      'news_filter_announcements': 'Annonces',
      'news_filter_news': 'Actualités',
      'news_filter_events': 'Événements',
      'news_empty': 'Aucune actualité ou événement disponible',
      'news_failed_to_load': 'Échec du chargement des actualités',
      'news_comments': 'Commentaires',
      'news_comments_count': '{count} commentaires',
      'news_no_comments':
          'Aucun commentaire pour le moment. Soyez le premier à partager votre avis !',
      'news_add_comment_hint': 'Ajouter un commentaire…',
      'news_post_comment': 'Publier',
      'news_comment_posted': 'Commentaire publié avec succès !',
      'news_comment_empty_error':
          'Veuillez saisir un commentaire avant de publier.',
      'news_like_error':
          'Impossible de mettre à jour le like. Veuillez réessayer.',
      'news_like_unsupported':
          'Les mentions J’aime ne sont pas disponibles pour cet élément.',
      'news_label_breaking': 'Flash',
      'news_label_event': 'Événement',
      'news_label_announcement': 'Annonce',
      'profile_failed_to_load': 'Échec du chargement du profil : {error}',
      'directory_title': 'Annuaire professionnel',
      'directory_search_hint': 'Rechercher des professionnels…',
      'directory_category_all': 'Tout',
      'directory_category_members': 'Membres',
      'directory_category_managers': 'Gestionnaires',
      'directory_no_branch':
          'Impossible de déterminer votre branche. Veuillez contacter le support.',
      'directory_empty_query': 'Aucun professionnel trouvé pour « {query} »',
      'directory_empty_category':
          'Aucun professionnel trouvé dans cette catégorie',
      'directory_empty_suggestion':
          'Essayez d’ajuster votre recherche ou le filtre de catégorie',
      'directory_failed_load_professionals':
          'Échec du chargement des professionnels',
      'directory_failed_load_profile': 'Échec du chargement du profil',
      'directory_rating_reviews': '{rating} • {reviews} avis',
      'directory_rating_reviews_zero': '{rating} • Aucun avis pour le moment',
      'directory_profession_fallback': 'Professionnel',
      'directory_location_placeholder': 'Localisation non spécifiée',
      'surveys_refresh_tooltip': 'Rafraîchir et déboguer',
      'surveys_test_tooltip': 'Tester l’API des réponses',
      'surveys_debug_info_title': 'Informations de débogage',
      'surveys_debug_close': 'Fermer',
      'surveys_debug_surveys_status': 'État des enquêtes : {status}',
      'surveys_debug_profile_status': 'État du profil utilisateur : {status}',
      'surveys_debug_user_id': 'ID utilisateur : {id}',
      'surveys_debug_count': 'Nombre d’enquêtes : {count}',
      'surveys_test_title': 'Test de l’API des réponses',
      'surveys_test_status_code': 'Code d’état : {code}',
      'surveys_test_success': 'Succès : {success}',
      'surveys_test_body': 'Corps : {body}',
      'surveys_already_completed': 'Vous avez déjà répondu à cette enquête',
      'surveys_checking_status': 'Vérification du statut…',
      'surveys_status_error': 'Erreur lors de la vérification : {error}',
      'surveys_empty_completed_title': 'Aucune enquête complétée',
      'surveys_empty_completed_subtitle':
          'Vous n’avez pas encore complété d’enquête.',
      'surveys_empty_pending_title': 'Aucune enquête en attente',
      'surveys_empty_pending_subtitle':
          'Toutes les enquêtes ont été complétées !',
      'surveys_empty_all_title': 'Aucune enquête disponible',
      'surveys_empty_all_subtitle':
          'Aucune enquête n’est disponible pour votre branche pour le moment.',
      'surveys_error_title': 'Échec du chargement des enquêtes',
      'surveys_retry': 'Réessayer',
      'surveys_filter_all': 'Toutes',
      'surveys_filter_completed': 'Terminées',
      'surveys_filter_uncompleted': 'En attente',
      'surveys_status_completed': 'Terminée',
      'surveys_status_pending': 'En cours',
      'surveys_status_expired': 'Expirée',
      'surveys_status_start': 'Commencer',
      'surveys_status_submitting': 'Envoi de l’enquête…',
      'surveys_loading_title': 'Chargement de l’enquête…',
      'surveys_submit_success': 'Enquête envoyée avec succès !',
      'surveys_submit_error': 'Échec de l’envoi de l’enquête : {error}',
      'surveys_question_single': '{count} question',
      'surveys_question_plural': '{count} questions',
      'surveys_dialog_title': 'Enquête rapide',
      'surveys_dialog_hint': 'Saisissez votre réponse…',
      'surveys_option_yes_very_satisfied': 'Oui, très satisfait',
      'surveys_option_needs_improvement':
          'Non, des améliorations sont nécessaires',
      'surveys_option_yes_definitely': 'Oui, certainement',
      'surveys_option_no_probably_not': 'Non, probablement pas',
      'surveys_option_very_likely': 'Très probable',
      'surveys_option_not_likely': 'Peu probable',
      'surveys_option_yes': 'Oui',
      'surveys_option_no': 'Non',
      'surveys_button_skip': 'Ignorer',
      'surveys_button_submit': 'Envoyer',
      'surveys_button_next': 'Suivant',
      'chat_default_title': 'Discussion',
      'chat_messages_title': 'Messages',
      'chat_group_type': 'Groupe',
      'chat_user_type': 'Utilisateur',
      'chat_failed_to_load_messages':
          'Échec du chargement des messages : {error}',
      'chat_empty_title': 'Aucun message pour l’instant',
      'chat_empty_subtitle': 'Démarrez une conversation avec quelqu’un',
      'chat_new_chat': 'Démarrer une nouvelle discussion',
      'chat_unknown_chat': 'Discussion inconnue',
      'chat_time_d_ago': 'Il y a {days} j',
      'chat_time_h_ago': 'Il y a {hours} h',
      'chat_time_m_ago': 'Il y a {minutes} min',
      'chat_time_just_now': 'À l’instant',
      'chat_online_status': 'En ligne',
      'chat_backend_error':
          'Erreur du backend. Veuillez actualiser ou contacter le support.',
      'chat_endpoint_not_found':
          'Point de terminaison de discussion introuvable sur le backend',
      'chat_sql_error': 'Erreur SQL du backend - veuillez contacter le support',
      'chat_resolve_wrong_chat':
          'La résolution a renvoyé une mauvaise discussion. Veuillez réessayer plus tard.',
      'chat_unable_to_resolve': 'Impossible de résoudre la discussion',
      'chat_failed_to_send': 'Échec de l’envoi du message',
      'chat_server_error':
          'Erreur du serveur. Veuillez réessayer plus tard ou contacter le support.',
      'chat_login_again': 'Veuillez vous reconnecter.',
      'chat_permission_denied':
          'Vous n’avez pas la permission d’envoyer des messages.',
      'chat_invalid_message':
          'Message invalide. Veuillez vérifier votre saisie.',
      'chat_new_search_hint': 'Rechercher des utilisateurs ou des branches…',
      'chat_new_search_title': 'Rechercher des personnes',
      'chat_new_search_subtitle':
          'Trouvez des utilisateurs ou des branches pour démarrer une conversation',
      'chat_new_no_results_title': 'Aucun résultat',
      'chat_new_no_results_subtitle':
          'Aucun utilisateur ou branche trouvé pour « {query} »',
      'chat_new_error_title': 'Recherche échouée',
      'chat_new_start_failed': 'Impossible de démarrer la discussion : {error}',
      'chat_new_title': 'Nouvelle discussion',
      'chat_badge_branch': 'Branche',
      'chat_type_message_hint': 'Écrire un message…',
      'time_period_am': 'AM',
      'time_period_pm': 'PM',
      'cart_title': 'Panier',
      'cart_empty_title': 'Votre panier est vide',
      'cart_empty_subtitle': 'Ajoutez des produits pour commencer',
      'cart_total_items_label': 'Articles au total :',
      'cart_select_items': 'Sélectionnez des articles pour payer',
      'cart_proceed_button': 'Passer au paiement ({count})',
      'cart_error_unavailable': 'Panier indisponible',
      'cart_update_failed': 'Échec de la mise à jour : {error}',
      'cart_item_removed': 'Article retiré du panier',
      'cart_delete_failed': 'Échec de la suppression de l’article : {error}',
      'cart_check_subscription': 'Vérification du statut de l’abonnement…',
      'cart_subscription_pending_title': 'Abonnement en attente d’approbation',
      'cart_subscription_pending_message':
          'Votre demande d’abonnement est en attente d’approbation. Veuillez patienter avant de continuer au paiement.',
      'common_ok': 'OK',
      'common_cancel': 'Annuler',
      'common_retrying': 'Nouvelle tentative…',
      'checkout_title': 'Paiement',
      'checkout_no_items_title': 'Aucun article sélectionné pour le paiement',
      'checkout_no_items_subtitle':
          'Veuillez sélectionner des articles dans votre panier.',
      'checkout_shipping_address': 'Adresse de livraison',
      'checkout_order_items': 'Articles de la commande',
      'checkout_payment_methods': 'Moyens de paiement',
      'checkout_place_order': 'Passer la commande - Rs. {total}',
      'checkout_processing_order': 'Traitement de votre commande…',
      'checkout_select_address_required':
          'Veuillez sélectionner une adresse de livraison',
      'checkout_no_items_selected':
          'Aucun article sélectionné pour le paiement',
      'checkout_failed_load_cart': 'Échec du chargement du panier : {error}',
      'checkout_order_summary': 'Récapitulatif de la commande',
      'checkout_summary_items': 'Articles',
      'checkout_summary_subtotal': 'Sous-total',
      'checkout_summary_shipping': 'Frais de livraison',
      'checkout_summary_tax': 'Taxes ({rate} %)',
      'checkout_summary_total': 'Total',
      'checkout_addresses_empty_title':
          'Aucune adresse de livraison enregistrée',
      'checkout_addresses_empty_subtitle':
          'Ajoutez une adresse de livraison pour poursuivre le paiement',
      'checkout_addresses_add_button': 'Ajouter une adresse de livraison',
      'checkout_address_select_placeholder':
          'Sélectionner une adresse de livraison',
      'checkout_addresses_none_title': 'Aucune adresse trouvée',
      'checkout_addresses_none_subtitle':
          'Ajoutez votre première adresse pour continuer',
      'checkout_addresses_error_generic': 'Échec du chargement des adresses',
      'checkout_addresses_error_network': 'Pas de connexion Internet',
      'checkout_addresses_error_generic_subtitle':
          'Une erreur est survenue. Veuillez réessayer.',
      'checkout_addresses_error_network_subtitle':
          'Veuillez vérifier votre connexion Internet et réessayer.',
      'checkout_retrying': 'Nouvelle tentative…',
      'checkout_add_address_title': 'Ajouter une nouvelle adresse',
      'checkout_field_first_name': 'Prénom *',
      'checkout_field_first_name_required': 'Le prénom est requis',
      'checkout_field_last_name': 'Nom *',
      'checkout_field_last_name_required': 'Le nom est requis',
      'checkout_field_address_line1': 'Adresse ligne 1 *',
      'checkout_field_address_required': 'L’adresse est requise',
      'checkout_field_city': 'Ville',
      'checkout_field_state': 'État/Province',
      'checkout_field_zip': 'Code postal',
      'checkout_field_country': 'Pays',
      'checkout_field_phone': 'Téléphone',
      'checkout_set_default_address': 'Définir comme adresse principale',
      'checkout_cancel': 'Annuler',
      'checkout_add_address': 'Ajouter l’adresse',
      'checkout_address_success': 'Adresse ajoutée avec succès !',
      'checkout_address_error': 'Échec de l’ajout de l’adresse : {error}',
      'checkout_order_failed': 'Échec de la commande : {error}',
      'checkout_payment_processing': 'Traitement…',
      'checkout_submit_request': 'Soumettre la demande',
      'checkout_pay_amount': 'Payer {amount} \$',
      'checkout_item_unit': 'Prix unitaire : Rs. {price}',
      'checkout_item_quantity': 'Quantité : {quantity}',
      'subscription_selection_title': 'Choisir un abonnement',
      'subscription_selection_heading': 'Choisissez votre formule',
      'subscription_selection_badge_popular': 'Le plus populaire',
      'subscription_selection_button_contact_sales': 'Contacter les ventes',
      'subscription_selection_button_choose': 'Choisir {plan}',
      'subscription_selection_button_choose_generic': 'Choisir la formule',
      'subscription_selection_error':
          'Erreur lors du chargement des abonnements : {error}',
      'subscription_checkout_title': 'Paiement',
      'subscription_checkout_user_success':
          'Votre abonnement a été enregistré. Attendez l’approbation de l’administrateur.',
      'subscription_checkout_member_success':
          'Votre demande d’abonnement a été soumise avec succès. Veuillez patienter le temps de l’approbation de votre compte.',
      'subscription_checkout_vendor_success':
          'Votre paiement a été effectué avec succès. Veuillez patienter le temps de l’approbation de votre compte.',
      'subscription_checkout_activation_failed':
          'L’activation de l’abonnement a échoué : {error}',
      'subscription_checkout_request_failed':
          'La demande d’abonnement a échoué : {error}',
      'subscription_checkout_payment_failed': 'Le paiement a échoué : {error}',
      'subscription_checkout_user_not_authenticated':
          'Utilisateur non authentifié',
      'subscription_checkout_processing': 'Traitement…',
      'subscription_checkout_submit_request': 'Soumettre la demande',
      'subscription_checkout_pay_amount': 'Payer {amount} \$',
      'subscription_summary_plan_label': 'Forfait {plan}',
      'subscription_summary_includes': 'Comprend :',
      'subscription_checkout_error': 'Erreur : {error}',
      'subscription_order_summary': 'Récapitulatif',
      'subscription_order_subtotal': 'Sous-total',
      'subscription_order_discount': 'Remise',
      'subscription_order_total': 'Total',
      'order_confirmation_title': 'Confirmation de commande',
      'order_success_message': 'Commande passée avec succès !',
      'order_number_display': 'Commande n°{number}',
      'order_summary_title': 'Récapitulatif de commande',
      'order_summary_subtotal': 'Sous-total',
      'order_summary_shipping_fee': 'Frais de livraison',
      'order_summary_tax': 'Taxes',
      'order_summary_total': 'Total',
      'order_number_label': 'Numéro de commande',
      'order_status_label': 'Statut',
      'order_payment_status_label': 'Statut du paiement',
      'order_total_amount_label': 'Montant total',
      'order_shipping_address_title': 'Adresse de livraison',
      'order_items_title': 'Articles de la commande',
      'order_items_empty': 'Aucun article dans cette commande.',
      'order_item_quantity': 'Qté : {quantity}',
      'order_item_price': 'Rs. {price}',
      'order_product_fallback': 'Produit',
      'order_back_to_cart': 'Retour au panier',
      'order_continue_shopping': 'Continuer vos achats',
      'order_status_pending': 'En attente',
      'order_status_processing': 'En cours',
      'order_status_completed': 'Terminée',
      'order_status_cancelled': 'Annulée',
      'order_payment_status_paid': 'Payé',
      'order_payment_status_unpaid': 'Non payé',
      'order_payment_status_refunded': 'Remboursé',
      'order_payment_status_pending': 'En attente',
      'order_payment_status_failed': 'Échec',
      'order_details_title': 'Détails de la commande',
      'order_details_load_failed': 'Échec du chargement des détails',
      'order_detail_ordered_on': 'Commandé le {date}',
      'order_payment_status_display': 'Paiement : {status}',
      'order_detail_sku': 'SKU : {sku}',
      'order_phone_label': 'Téléphone : {phone}',
      'order_review_section_title': 'Évaluez les produits que vous avez reçus',
      'order_review_section_subtitle':
          'Partagez votre expérience avec les produits reçus',
      'order_review_rating_label': 'Note *',
      'order_review_title_label': 'Titre de l’avis (optionnel)',
      'order_review_title_hint': 'Résumez votre expérience',
      'order_review_body_label': 'Votre avis (optionnel)',
      'order_review_body_hint': 'Partagez votre ressenti sur ce produit',
      'order_review_submit_button': 'Envoyer l’avis',
      'order_review_select_rating_error': 'Veuillez sélectionner une note',
      'order_review_submit_success': 'Avis envoyé pour {product}',
      'order_review_submit_error': 'Échec de l’envoi de l’avis : {error}',
      'companies_title': 'ORGANES',
      'organes_title': 'ORGANES',
      'organes_divisions': 'Divisions',
      'organes_effectif': 'Effectif',
      'organes_agents': 'Agents',
      'organes_search_hint': 'Recherche',
      'organes_description': 'Description',
      'organes_contact': 'Contact',
      'organes_province': 'Province',
      'organes_departement': 'Département',
      'organes_commune': 'Commune / Localité',
      'organes_arrondissement': 'Arrondissemnt',
      'companies_description':
          'Connecter les bâtisseurs, favoriser le développement et renforcer la communauté.',
      'companies_section_title': 'Nos entreprises',
      'companies_empty_state': 'Aucune entreprise trouvée',
      'companies_error_loading': 'Erreur lors du chargement des entreprises',
      'events_calendar_title': 'Calendrier',
      'events_day_sun': 'Dim',
      'events_day_mon': 'Lun',
      'events_day_tue': 'Mar',
      'events_day_wed': 'Mer',
      'events_day_thu': 'Jeu',
      'events_day_fri': 'Ven',
      'events_day_sat': 'Sam',
      'events_filter_all': 'Tout',
      'events_filter_events': 'Événements',
      'events_filter_meetings': 'Réunions',
      'events_today_title': 'Événements du jour',
      'events_no_events_for_date': 'Aucun événement pour cette date',
      'events_upcoming_title': 'Événements à venir',
      'events_no_location': 'Aucun lieu',
      'events_scope_global': 'Global',
      'events_scope_branch': 'Branche',
      'events_all_day': 'Toute la journée',
      'events_error_title': 'Échec du chargement des événements',
      'events_date_start': 'Date de début',
      'events_date_end': 'Date de fin',
      'events_location': 'Emplacement',
      'events_contact_person': 'Personne à contacter',
      'events_no_contact_person': 'Aucune personne de contact disponible',
      'detail_author': 'Auteur',
      'detail_author_label': 'Auteur : ',
      'detail_at': 'à',
      'profile_error_load': 'Échec du chargement du profil',
      'profile_plan_unknown': 'Inconnu',
      'profile_personal_info_title': 'Informations personnelles',
      'profile_personal_full_name': 'Nom complet',
      'profile_personal_email': 'Adresse e-mail',
      'profile_personal_phone': 'Numéro de téléphone',
      'profile_personal_member_since': 'Membre depuis',
      'profile_personal_member_since_unknown': 'Non disponible',
      'profile_personal_edit': 'Modifier les informations',
      'profile_address_hint': 'Adresse',
      'profile_business_name': "Nom de l’entreprise",
      'profile_shop_details': 'Détails de la boutique',
      'profile_update_name_required': 'Le nom est requis',
      'profile_update_phone_required': 'Le numéro de téléphone est requis',
      'profile_update_success': 'Profil mis à jour avec succès !',
      'profile_update_failed': 'Échec de la mise à jour du profil : {error}',
      'profile_update_in_progress': 'Mise à jour…',
      'profile_update_button': 'Mettre à jour le profil',
      'edit_profile_pick_image_failed': "Échec du choix de l’image : {error}",
      'edit_profile_load_error': 'Échec du chargement du profil : {error}',
      'profile_orders_title': 'Mes commandes',
      'profile_orders_refreshing': 'Actualisation…',
      'profile_orders_refresh_tooltip': 'Actualiser les commandes',
      'profile_orders_empty_title': 'Aucune commande pour le moment',
      'profile_orders_empty_subtitle': 'Vos commandes apparaîtront ici',
      'profile_orders_error_title': 'Échec du chargement des commandes',
      'common_not_available': 'N/D',
      'logout': 'Se déconnecter',
      'notifications_header_title': 'Restez connecté',
      'notifications_header_subtitle':
          'Recevez des notifications personnalisées pour les rappels, les nouvelles publications et les mises à jour importantes',
      'notifications_settings_title': 'Paramètres des notifications',
      'notifications_event_title': 'Rappels d’événements',
      'notifications_event_subtitle': 'Soyez averti avant les événements',
      'notifications_posts_title': 'Nouvelles publications',
      'notifications_posts_subtitle':
          'Restez informé des dernières publications',
      'notifications_announcements_title': 'Annonces',
      'notifications_announcements_subtitle':
          'Mises à jour importantes de l’association',
      'notifications_recent_title': 'Notifications récentes',
      'notifications_empty': 'Aucune notification pour le moment',
      'notifications_load_failed': 'Échec du chargement des notifications',
      'notifications_mark_read_success': 'Notification marquée comme lue',
      'notifications_mark_read_failure':
          'Impossible de marquer la notification comme lue : {error}',
      'notifications_badge_new': 'NOUVEAU',
      'notifications_smart_title': 'Notifications intelligentes',
      'notifications_smart_subtitle': 'Personnalisez votre expérience',
      'notifications_sound': 'Son',
      'notifications_vibration': 'Vibration',
      'profile_membership_title': 'Statut de l’abonnement',
      'profile_membership_current_plan': 'Formule actuelle',
      'profile_membership_expiry': 'Date d’expiration',
      'profile_membership_expired_body': 'Votre abonnement a expiré',
      'profile_membership_days_remaining': 'Jours restants',
      'profile_membership_day_singular': '{count} jour',
      'profile_membership_days_plural': '{count} jours',
      'profile_membership_progress_title': 'Progression de l’abonnement',
      'profile_vendor_status_title': 'Statut du vendeur',
      'profile_user_subscription': 'Statut de l’abonnement utilisateur',
      'membership_no_subscription_title': 'Aucun abonnement pour le moment',
      'membership_no_subscription_user_hint':
          'Abonnez-vous pour accéder aux fonctionnalités premium',
      'membership_no_subscription_vendor_hint':
          'Obtenez un abonnement vendeur pour accéder à toutes les fonctionnalités',
      'membership_no_subscription_member_hint':
          'Obtenez un abonnement pour accéder à toutes les fonctionnalités',
      'membership_pending_title': 'Abonnement en attente',
      'membership_pending_message':
          'Votre demande d’abonnement est en attente d’approbation. Veuillez patienter.',
      'membership_active_title': 'Abonnement actif',
      'membership_active_message':
          'Votre abonnement est actif et vous avez accès à toutes les fonctionnalités.',
      'membership_expired_title': 'Abonnement expiré',
      'membership_expired_message':
          'Votre abonnement a expiré. Renouvelez-le pour continuer à profiter des fonctionnalités premium.',
      'membership_progress_expired': 'L’abonnement a expiré',
      'membership_progress_expires_tomorrow': 'Expire demain',
      'membership_progress_expires_soon':
          'Expire dans {count} jours - renouvelez bientôt !',
      'membership_progress_expires_days': 'Expire dans {count} jours',
      'membership_progress_just_started':
          'Abonnement juste commencé ({remaining} sur {total} jours restants)',
      'membership_progress_early':
          'Début de période ({remaining} sur {total} jours restants)',
      'membership_progress_midway':
          'Milieu de période ({remaining} sur {total} jours restants)',
      'membership_progress_near_end':
          'Fin de période ({remaining} sur {total} jours restants)',
      'drawer_explore_services': 'Découvrez nos services et restez connectés.',
      'drawer_footer': '© 2024 Association UDB. Tous droits réservés.',
      'drawer_premium_title': 'Devenez membre premium',
      'drawer_premium_description':
          'Déverrouillez des avantages exclusifs pour enrichir votre expérience.',
      'survey_analysis_title': 'Enquête UDB',
      'survey_analysis_total_responses': 'Réponses totales',
      'survey_analysis_active_surveys': 'Enquêtes actives',
      'survey_analysis_recent_title': 'Enquêtes récentes',
      'survey_analysis_questions_responses':
          '{questions} questions • {responses}/{total} réponses',
      'survey_analysis_completion_rate': 'Taux de complétion',
      'survey_analysis_analytics_title': 'Analyses',
      'survey_analysis_responses_over_time':
          'Réponses aux enquêtes dans le temps',
      'survey_analysis_error_title':
          'Échec du chargement de l’analyse des enquêtes',
      'all_surveys_title': 'Toutes les enquêtes',
      'all_surveys_empty_title': 'Aucune enquête disponible',
      'all_surveys_empty_subtitle': 'Aucune enquête à afficher.',
      'all_surveys_count_single': '{count} enquête',
      'all_surveys_count_plural': '{count} enquêtes',
      'all_surveys_error_title': 'Échec du chargement des enquêtes',
      'statistics_title': 'Statistiques et analyses',
      'statistics_error_title': 'Échec du chargement des statistiques',
      'statistics_overview': 'Aperçu',
      'statistics_total_orders': 'Commandes totales',
      'statistics_total_revenue': 'Revenu total',
      'statistics_total_customers': 'Clients totaux',
      'statistics_avg_order_value': 'Valeur moyenne des commandes',
      'statistics_currency_value': '{value} \$',
      'statistics_sales_progress_title': 'Progression des ventes ({period})',
      'statistics_period_weekly': 'Hebdomadaire',
      'statistics_period_monthly': 'Mensuel',
      'statistics_period_yearly': 'Annuel',
      'statistics_select_month': 'Sélectionner un mois',
      'statistics_week_label': 'Semaine {week}',
      'statistics_select_week_title': 'Sélectionner une semaine - {month}',
      'statistics_order_status_title': 'Statut des commandes',
      'statistics_orders_count': '{count} commandes',
      'statistics_status_pending': 'En attente',
      'statistics_status_processing': 'En traitement',
      'statistics_status_shipped': 'Expédiée',
      'statistics_status_delivered': 'Livrée',
      'manager_statistics_title': 'Statistiques et rapports',
      'manager_statistics_members': 'Membres totaux',
      'manager_statistics_events': 'Événements totaux',
      'manager_statistics_monthly_progress': 'Progression mensuelle',
      'manager_statistics_quick_stats': 'Statistiques rapides',
      'manager_statistics_new_subscriptions': 'Nouveaux abonnements',
      'manager_statistics_this_month': 'Ce mois-ci',
      'manager_statistics_events_organized': 'Événements organisés',
      'manager_statistics_subscription_trends': 'Tendances des abonnements',
      'manager_statistics_select_duration': 'Sélectionner une durée',
      'manager_statistics_duration_last_month': 'Le mois dernier',
      'manager_statistics_duration_last_6_months': 'Les 6 derniers mois',
      'manager_statistics_duration_last_year': 'L’année dernière',
      'manager_statistics_legend_new': 'Nouveaux',
      'manager_statistics_legend_renewed': 'Renouvelés',
      'manager_statistics_error_subscriptions':
          'Échec du chargement des abonnements',
      'drawer_become_member_button': 'Devenir membre',
      'drawer_survey_analysis': 'Analyse des enquêtes',
      'drawer_error_title': 'Impossible de charger le menu',
      'profile_header_title': 'Mon profil',
      'profile_header_member_id': 'ID membre : {id}',
      'profile_header_member_id_default': 'ID membre : UDB-2024-001',
      'profile_header_become_member': 'Devenir membre',
      'footer_become_member_snackbar':
          'Devenez membre pour accéder à cette fonctionnalité.',
      'profile_header_become_vendor': 'Devenir vendeur',
      'profile_badge_basic': 'Membre basique',
      'profile_badge_standard': 'Membre standard',
      'profile_badge_premium': 'Membre premium',
      'product_detail_title': 'Détail du produit',
      'product_detail_not_found': 'Produit introuvable',
      'product_detail_not_available': 'Produit indisponible',
      'product_detail_discount_badge': '-{percent} %',
      'product_detail_reviews_summary': '{rating} ({count} avis)',
      'product_detail_customer_reviews': 'Avis clients',
      'product_detail_reviews_count': '{count} avis',
      'product_detail_reviews_count_zero': '0 avis',
      'product_detail_no_reviews_yet': 'Aucun avis pour le moment',
      'product_detail_be_first_review': 'Soyez le premier à laisser un avis sur ce produit !',
      'product_detail_load_more_reviews': 'Charger plus d\'avis',
      'product_detail_failed_to_load_reviews': 'Échec du chargement des avis',
      'product_detail_reviews_try_again': 'Veuillez réessayer plus tard.',
      'product_detail_review_anonymous': 'Anonyme',
      'product_detail_review_verified': 'Avis vérifié',
      'product_detail_in_stock': 'En stock ({count} disponibles)',
      'product_detail_out_of_stock': 'Rupture de stock',
      'product_detail_description_title': 'Description',
      'product_detail_specifications_title': 'Caractéristiques',
      'product_detail_spec_sku': 'SKU',
      'product_detail_spec_weight': 'Poids',
      'product_detail_spec_weight_value': '{weight} kg',
      'product_detail_spec_dimensions': 'Dimensions',
      'product_detail_shop_info_title': 'Informations sur la boutique',
      'product_detail_no_tagline': 'Aucun slogan disponible',
      'product_detail_related_products_title': 'Produits associés',
      'product_detail_add_to_cart': 'Ajouter au panier',
      'product_detail_add_to_cart_success':
          '{product} a été ajouté au panier !',
      'product_detail_add_to_cart_error':
          'Échec de l’ajout au panier : {error}',
      'product_detail_video_error_empty': 'URL vidéo vide',
      'product_detail_video_error_unreachable':
          'Impossible d’atteindre l’URL vidéo',
      'product_detail_video_error_playback': 'Erreur de lecture vidéo',
      'product_detail_video_error_initialization':
          'Échec de l’initialisation de la vidéo',
      'product_detail_video_loading': 'Chargement de la vidéo…',
      'orders_empty_title': 'Aucune commande pour le moment',
      'orders_empty_subtitle':
          'Vos commandes apparaîtront ici après vos achats',
      'orders_start_shopping': 'Commencer vos achats',
      'orders_unavailable': 'Commandes indisponibles',
      'orders_check_connection': 'Vérifier la connexion',
      'orders_load_more': 'Charger plus de commandes',
      'orders_load_more_failed':
          'Impossible de charger plus de commandes : {error}',
      'common_loading': 'Chargement…',
      'common_user_placeholder': 'Utilisateur',
      'membership_dialog_title': 'Choisissez un type d’abonnement',
      'membership_dialog_subtitle':
          'Sélectionnez le type d’abonnement que vous souhaitez acheter :',
      'membership_option_member_title': 'Devenir membre',
      'membership_option_member_description':
          'Accédez aux fonctionnalités et avantages premium des membres',
      'membership_option_vendor_title': 'Devenir vendeur',
      'membership_option_vendor_description':
          'Vendez des produits et gérez votre boutique',
      'membership_option_user_title': 'Devenir utilisateur spécial',
      'membership_option_user_description':
          'Accédez aux fonctionnalités et privilèges spéciaux',
      'subscription_subscribe_now': 'S’abonner maintenant',
      'subscription_renew_button': 'Renouveler l’abonnement',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final languageCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    final base =
        _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    if (params == null || params.isEmpty) {
      return base;
    }
    var resolved = base;
    params.forEach((paramKey, value) {
      resolved = resolved.replaceAll('{$paramKey}', value);
    });
    return resolved;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension LocalizationBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

extension LocalizationStringExtension on String {
  String tr(BuildContext context, {Map<String, String>? params}) =>
      AppLocalizations.of(context).translate(this, params: params);
}
